name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

    deploy:
      
        name: Deploy
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:
        
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Login
          uses: "google-github-actions/auth@v1"
          with:
            credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
            service_account: "zamiast@zamiast-project-example.iam.gserviceaccount.com"


        # - name: Set up gcloud
        #   uses: google-github-actions/setup-gcloud@v0




        - name: Configure Docker
          run: gcloud auth configure-docker --quiet
            
        - name: Build Docker image
          run: docker build . --tag $IMAGE_NAME 

        - name: Test Docker image
          run: docker run $IMAGE_NAME sh -c "go test -v" 

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region us-central1 --platform managed --allow-unauthenticated
